-- Generated by the SpeakStone voice pipeline. Do not hand-edit.
--
-- SAMPLE DATA: placeholder entries showing the format until the pipeline
-- writes the real file. See the format notes in QuestAudioLibraryUI.lua.
--
-- Tags are a race code followed by one sex letter: M, F or N (none/other).
-- Quests take one tag for all three clips, or a table with d/p/c for
-- description, progress and completion when the voices differ.
SpeakStone_VoiceInfo = {
    format = 1,
    races = {
        Hu = "Human", Dw = "Dwarf", NE = "Night Elf", Gn = "Gnome",
        Dr = "Draenei", Wo = "Worgen", Or = "Orc", Un = "Undead",
        Ta = "Tauren", Tr = "Troll", BE = "Blood Elf", Go = "Goblin",
        Pa = "Pandaren", Vu = "Vulpera", Dc = "Dracthyr", Ea = "Earthen",
    },
    npc = {
        [197] = "HuM", -- Marshal McBride
        [240] = "HuM", -- Marshal Dughan
    },
    quest = {
        [783] = "HuM",
        [33] = { d = "HuM", p = "HuM", c = "HuF" },
    },
}
