-- Auto-generated by tools/build_gossip_texts.py. The gossip text each
-- captured variant was voiced from, normalised exactly as
-- SpeakStone_Main.lua's NormalizeGossipText does, so the live
-- GOSSIP_SHOW text can be matched to the right clip. Regenerate with
-- that script after any harvest; never hand-edit.
SpeakStone_GossipTexts = {
[68]={ -- Stormwind City Guard
  ["What do you need directions to?"]=1,
},
[240]={ -- Marshal Dughan
  ["Ach, it's hard enough keeping order around here without all these new troubles popping up! I hope you have good news, adventurer..."]=1,
},
[2119]={ -- Dannal Stern
  ["Do not waste my time, mage."]=1,
},
[2122]={ -- David Trias
  ["I can not train you. You need to talk to your class trainer."]=1,
},
[2198]={ -- Crier Goodman
  ["Greetings and salutations, hero! I have the latest news from both continents and points beyond for your consideration."]=1,
},
[3448]={ -- Tonga Runetotem
  ["The times we live in are as fickle as the shifting winds, druid. The ground itself quakes and cries out in anguish. We must remain resolute or we ourselves will be engulfed by the turmoil."]=1,
},
[3934]={ -- Innkeeper Boorand Plainswind
  ["As the wind on the plains, you are always welcome here."]=1,
},
[5512]={ -- Kaita Deepforge
  ["Don't let the humans in the Bazaar fool ye lass, with the subway those gnomes built it's easier than ye might think to transport goods from Ironforge. If they try to tack on import fees just tell them yer gonna buy yer gear from me."]=1,
},
[8738]={ -- Vazario Linkgrease
  ["Greetings! If you are here to access goblin engineering schemata, please know we only interface with certified goblin engineers."]=1,
},
[8962]={ -- Nida
  ["I think my necklace fell in the lake. My daddy got it for me, and he's gonna be mad now."]=1,
},
[9981]={ -- Sikwa
  ["Greetings, druid. I can assist you in recovering lost companions."]=1,
},
[16418]={ -- Mupsi Shacklefridd
  ["You'd better not be causing trouble, adventurer!"]=1,
},
[29725]={ -- Benik Boltshear
  ["How is a locksmith supposed to make a living in a world with no locked doors?"]=1,
},
[38895]={ -- Lilian Voss
  ["Get away from me, you abomination!"]=1,
  ["The undead are a taint upon Azeroth! Every one of you creatures deserves to be destroyed!"]=2,
},
[38910]={ -- Lilian Voss
  ["Get away from me, you monster! Don't look at me! I'm hideous!"]=1,
},
[44238]={ -- Harrison Jones
  ["Are you here to train in Archaeology?"]=1,
},
[49230]={ -- Marshal Redpath
  ["Stand back, monster. You want to fight? Because I'll fight you. I'll fight any one of you creatures! Do you hear me?"]=1,
  ["Oh really? Fine. I don't want to join you and your Forsaken. Maybe I'll start my own Forsaken! Maybe I'll invent Forsaken with elbows!"]=2,
},
[49231]={ -- Valdred Moray
  ["What... what's going on? Who are you? What happened to me?"]=1,
  ["I... died? Yes, you're right. I died. It was an orc... he cut off my hands, and left me to die. <Valdred looks down at his hands.> These aren't my hands! THESE AREN'T MY HANDS!"]=2,
  ["<Valdred looks back down at his hands.> I suppose this is my fate then. Hah! Part of an undead army. Somehow I never considered that I might end up fighting for the Forsaken. <He looks back up at you.> What do I do now?"]=3,
},
[50027]={ -- Dargad
  ["I don't train your kind druid."]=1,
},
[50028]={ -- Chintoka
  ["Your will is not strong enough to manipulate the forces we control druid."]=1,
},
[50029]={ -- Egnom
  ["For too long we have ignored the secrets of the Arcane. Sadly, they will remain a secret to you."]=1,
},
[50032]={ -- Tarmod
  ["Don't waste my time."]=1,
},
[50033]={ -- Ging
  ["I don't train your kind, druid. Find your own trainer before you anger me."]=1,
},
[63272]={ -- Ting, Strong of Stomach
  ["I will say, the Forsaken have... strange taste when it comes to brew. I get the feeling they're not exactly preparing it for friends, though."]=1,
},
[78952]={ -- Coriander
  ["Please, sit and make yourself comfortable."]=1,
},
[85923]={ -- Rangari Laandon
  ["In my days with the rangari, I have learned many nuances of skinning the varied beasts of Draenor. Now that I am in Stormshield, however, I find it is much more enjoyable to pass these teachings onto others, than to toil in the fields with the skinning knife. Wouldn't you agree?"]=1,
},
[86175]={ -- Bregg Coppercast
  ["Are you sure you want to buy th'gear I've got for sale? Crunchpaw has th' best stuff these days. B'tween the two of us, I heard she didn't get her nickname from fightin' the Horde. Don't tell her I said that. Actually, I'd prefer y'din't even mention that we spoke. I'm not on her good side right now."]=1,
},
[87052]={ -- Artificer Harlaan
  ["I sell designs for the techniques used to harness the power of Draenor's crystals. If you are skilled enough, you may benefit greatly from this knowledge."]=1,
},
[87057]={ -- Leara Moonsilk
  ["Ready to turn those raggedy old leathers into something worth wearing?"]=1,
},
[87243]={ -- Zaalendor
  ["A model with skill such as mine does not come without dedication. I have spent a lifetime perfecting my signature poses."]=1,
},
[98148]={ -- Nassar
  ["You seem like the type that just wants a fight. If you're interested, the Horde needs more troops."]=1,
},
[129679]={ -- Shani Ward
  ["Welcome to my Inn, weary traveler. What can I do for you?"]=1,
},
[132215]={ -- Lightforged Vindicator
  ["Light be with you."]=1,
},
[133332]={ -- Statiks Quikfuse
  ["These machines are fantastic! How could they operate with no anomalies or chance of failure? Oh, excuse me. Did you need something?"]=1,
},
[188054]={ -- Azure Guardian
  ["Are you lost, dracthyr?"]=1,
},
[189479]={ -- Rumiastrasza
  ["Welcome to The Ruby Feast! Chef Morsel and I, the most stunning culinary duo in all the Isles, have prepared and laid out a most various array of flavorful delights! Dig in, dance, and enjoy the festivities!"]=1,
},
[189869]={ -- Valdrakken Citizen
  ["Welcome to Valdrakken, dracthyr!"]=1,
},
[189895]={ -- Valdrakken Citizen
  ["Who maintained these isles over the eons? We did! And what do we get for it? Nothing!"]=1,
  ["Hello, friend. Did you also get turned out of your home by the return of the \"masters\"?"]=2,
},
[191263]={ -- Salukan
  ["Where would you like to fly?"]=1,
},
[195540]={ -- Basran
  ["<You extend a hand to offer Basran pets, but he stays stoically next to his khan. Basran is currently working and you should not pet service dogs on duty.>"]=1,
},
[195606]={ -- Beastmaster Zira
  ["I've never met a beast I couldn't win over. I've worked with rockfangs, hornstriders, even thunder lizards! But no animal can beat a bakar in loyalty and honor."]=1,
},
[196087]={ -- Quartermaster Ashu
  ["Many different clans full of many different centaur bringing many different supplies... It is almost impossible to coordinate everything, but we do the best that we can."]=1,
},
[196449]={ -- Elder Odgerel
  ["Clan Teerai are the proud protectors of tradition and good values. This meeting at Maruukai is also our tradition."]=1,
},
[196725]={ -- Chef Sungshin Ironpaw
  ["Welcome, fellow traveler. I am Chef Sungshin Ironpaw, Guide to the Ways and administrant to the Halfhill Market. A curious letter made it's way to me in the Valley of the Four Winds, written by Chef Morsel. He informed me that these Isles had opened and that he and his partner would be hosting a garden party of sorts. They would use it as an opportunity to showcase the rare ingredients of the Dragon Isles, as well as the wide variety of cuisines Azeroth has to offer. I simply couldn't refuse a request to exhibit the wonders of our great Pandaria! Please feel free to try my own offerings. We Pandaren are always on the move, so we've found food that travels with you is always the most satisfying."]=1,
},
[197792]={ -- Banshi
  ["I go where da food be."]=1,
},
[235787]={ -- Lor'themar Theron
  ["Silvermoon is grateful for your aid."]=1,
},
[239670]={ -- Vaultkeeper Elysa
  ["How may I help you?"]=1,
},
[241703]={ -- Silvermoon Guard
  ["What do you seek, priest?"]=1,
},
[243229]={ -- Eldara Dawnrunner
  ["A sight to behold, is it not? Since the time of Dath'Remar, the elves have used this great forge to craft armor of unparalleled might. It is said that the flames were first stoked by the soul of a phoenix who thought it a fitting nest, and that its power still weaves itself through every creation. We will permit you to share in its gifts."]=1,
  ["The Catalyst can infuse great power into items, enhancing them and pushing their potential further than ever before!"]=2,
},
[243280]={ -- Theremis
  ["Which Midnight Specialization would you like to relearn?"]=1,
},
[243349]={ -- Dolothos
  ["Greetings. Are you seeking instruction in enchanting?"]=1,
},
[243357]={ -- Camberon
  ["Greetings. Are you seeking instruction in alchemy?"]=1,
},
[246607]={ -- Greenspeaker Cyenna
  ["We are blessed to live in Harandar, and we treat that as a responsibility. The roots of World Trees wind through these lands, and we must tend to them to make sure that they continue to thrive. I am Cyenna, Charge Nurse of Nordrassil. It is a responsibility I take very seriously."]=1,
},
[249046]={ -- Assistant Shadala
  ["New shipments of outfits, weapons and creatures come in every month. I make sure our displays always look their best."]=1,
},
[249187]={ -- Envoy Manat
  ["It is a great honor to represent Harandar in this grand city."]=1,
  ["Our banner should be outside by the natural beauty of the goddess, not locked within a hut."]=2,
},
[252312]={ -- Second Chair Pawdo
  ["Hello! Frederick's Fabulous Furniture, Pawdo speaking."]=1,
},
[252500]={ -- Ranger Telenus
  ["Train a dog, I said. How hard could it be, I said. I need to stop talking."]=1,
},
[253514]={ -- Orweyna
  ["Zul'jarra should know the history we saw with Zul'jan in the Den of Echoes. That's what he's doing all of this for. Because of what I showed him..."]=1,
},
[253515]={ -- Captain Tokka
  ["When we first wrecked on this island, I set my crew to explore. Look for supplies, allies, the like. I can tell ya what we know."]=1,
},
[253837]={ -- Apothecary Dezi
  ["Mmm... you look troubled. Headaches? Curses? Or just bad decisions? I treat all three, sometimes the same way."]=1,
},
[255473]={ -- Maren Silverwing
  ["Welcome, adventurer! Have you been aiding in the defense of Quel'Thalas against the recent incursions? I'd be happy to exchange your hard-earned Field Accolades for the new weapons and armor we've recently discovered. I'm also happy to exchange any Dark Particles you may find during these incursions for Field Accolades. My sister and the other ren'dorei are studying them in hopes of better understanding who and where these attacks are coming from."]=1,
  ["After Xal'atath's initial attack on the Sunwell, a hidden cache of armor and weapons was discovered in the wreckage. We believe some of these may have been stashed here since the Legion's takeover of the Sunwell Plateau. It took us a bit to catalogue and check for any unsafe anomalies that may have formed during the years they were hidden, but we've managed to sort through them all. With more volunteers joining the Ranger Captain's strike force, we're going to need all the weapons and armor we can get."]=2,
  ["<Maren glances at Mayven before looking back at you with a smile.> Yes. Twin sister, in fact. We both shared a common fondness for magic, which led us to pursue further studies within the Magister's Terrace. I went down one path... and she went down another. It's been a few years since our fallout, but I'm grateful she's back. She's may be a bit... cold sometimes but she's harmless. Well, mostly. <Maren scrunches her nose as if doubting her own words.>"]=3,
},
[255476]={ -- Triam Dawnsetter
  ["This is such an interesting find!"]=1,
  ["A small group of us have been studying some relics from the recent assault on the city. The items appear to have been infused with latent void magic, which I believe has greatly increased their potential. The items' physical properties have also been altered, giving them all a striking look! Interesting, isn't it? Once we are sure they pose no threat to our own, we can start outfitting our troops with them and use this power against our enemies!"]=2,
},
[255495]={ -- Rae'ana
  ["Greetings, human."]=1,
  ["The Ranger Captain acknowledges that my experience in relic study will be invaluable against the host of threats in the days ahead. Before this, I was cataloging relics for the Dragonscale Expedition. When our camp heard of the attack on the Sunwell, I joined those who raced to return home to Silvermoon. I have not forgotten when the people of Quel'Thalas rallied to defend Suramar years ago. I will help in any way I can."]=2,
},
[255499]={ -- Ji-eun
  ["Oh, hello there!"]=1,
  ["Young... I was the oldest Explorer-In-Training at the basecamp! Plus I had been starting to work with Rae'ana studying artifacts. She agreed to take me on as an apprentice. I have never been to a city like Silvermoon. It is so grand! We got to visit Valdrakken once, but there are so many more people here."]=2,
},
[257298]={ -- Loa Speaker Yl'mul
  ["All that's left here is me and de captain. De curse I cast keeps us from movin' on."]=1,
},
[257803]={ -- Tak'lejo
  ["My people, kidnapped! Stolen! Killed! Many more are missin'! And de hash'ey's brother walks free!"]=1,
  ["Ula'tek ain't a name I have heard before. If ya ask me to guess, it's a powerful serpent of some kind. A dead loa, maybe. Even when Zul'jin led de Amani, de only stories told of Atal'Utek were of a cursed temple built on a rocky sea. Exiles and criminals sometimes risked de boat ride here to escape Amani justice, never to be seen again."]=2,
},
[258859]={ -- Zul'jarra
  ["The elves have refused me. I shouldn't be so surprised. I rely on you now more than ever, my hash'ura."]=1,
  ["I know de justice of Zul'Aman and how we deal with traitors. If he weren't my brother, I would take his head and paint my face with his blood for all he's done. But he is my brother. And I'm de hash'ey. Anyone who wants Jan gotta come through me first. Damn it, Jan... I know why he's doin' it. I just... <Zul'jarra winces and rubs the gash where Zul'jan cut her.> I'm de one who can knock some sense into him. I know there's a way."]=2,
},
[258860]={ -- Lady Liadrin
  ["Zul'jan gave her that wound? That traitorous little..."]=1,
},
[260638]={ -- Silvermoon Guard
  ["What do you seek, priest?"]=1,
},
[261870]={ -- Captain Tokka
  ["It be good to see some fresh faces around here. My crew and I have been stranded for over seven years, and we were beginning to believe we'd have to rebuild society from scratch!"]=1,
  ["We'd been sailing Torga's Beak, a gift given to us by the Zandalari, when out of nowhere a great white serpent broke our hull. My crew acted quickly, and took us to shore before we took on too much water. Would have been better to let the ship sink and swim back to Zul'Aman, but little did we know the trap we had put ourselves in. After establishing ourselves on the island, we built small dinghies to escape--only to find the fogs constantly turning us back to shore. We've spent the last few years making this place a home. We had begun to acclimate, until just a day ago when the foul serpents poured forth from the mountainside. My crew scattered across this cursed island. What cruel winds, for the fog to lift only now."]=2,
  ["'Twas a cursed land, even before the snakes emerged. Many a crewmate found themselves attacked by the souls of the dead that wander here, and we've found a number of other Zandalari ships that met the fate of ours. To the north, we've made allies with a hermit by the name of Ofi, an Amani exile. She prefers to keep to herself, but is the only friendly face we've seen. To the east, the island turns to muck and mud, and a combination of murlocs and spirits make their home there. The murlocs have a crazed glint in their eyes... a curse that spread to some of my crewmates as well. As for the spirits, some of them seem friendly enough while others attack you on sight. We've generally found it best to avoid the dead."]=3,
  ["To the south lays Gnarldor Isle, where some burly giants seem to have taken home. They're none too friendly and we give them a wide berth. To the west are the crypts and temples where the snakes emerged from. My crew is a superstitious sort and don't like messing with graves, so we thought to leave the quiet lands alone. We didn't expect venom to spew from the mountains and flying snakes with two heads! You'd best be getting on with your soldiers. I could use your help around here later, but for now it seems we have an outpost to fortify. You're a ray of hope, Nerfwins."]=4,
},
[262204]={ -- Witherbark Cook
  ["The ingredients I've got are... suspicious at best. Eh, with your help I'm sure it'll be at least edible."]=1,
},
[263121]={ -- Mayven Ombrewing
  ["As you can no doubt tell, I am somewhat preoccupied with my research. Unless your question pertains to my work, please direct all matters to my sister, Maren."]=1,
  ["<Mayven closes her eyes as she slowly exhales before looking at you.> Yes, she is. If you're that curious about my familial relations, please feel free to ask her all about it. While you do that, I've got work that requires my attention. These dark particles aren't going to study themselves."]=2,
  ["<Mayven narrows her eyes at you for a moment before she gestures to the void magic circling around her hand.> Since you're so curious... I'm studying the dark particles left behind by these new threats. Why you may ask? Most types of magic leave behind a faint residue that can be used to determine the type of magic or in some cases, the reagents and fuel source used to power the spell. In this case, we are trying to unravel these particles to learn more about these threats and maybe find a way to counter their next move."]=3,
},
}
