#!/usr/bin/env python3
"""Build VoicedLines.lua: which NPC chat lines Blizzard has voiced.

The client gets no signal when an NPC's /say or /yell comes with a voice
recording, so the addon can't tell a voiced story beat from silent flavour
text. BroadcastText can: a row with a SoundKitID is voiced. This writes a
set of hashes of those rows' text, which SpeakStone_Main.lua checks each
CHAT_MSG_MONSTER_* line against, so narration gives way to every voiced line
and ignores the silent ones.

Only the rows the client ships are covered. Retail streams most older
BroadcastText from the server now, so this is mostly current content; the
addon keeps its per-NPC guess for anything not listed.

Usage:
    python tools/build_voiced_lines.py                     # latest retail
    python tools/build_voiced_lines.py --product wow_classic_beta   # Forever

The hash and the normalisation MUST match VoicedLineHash in
SpeakStone_Main.lua.
"""
import argparse
import csv
import io
import json
import re
import sys
import urllib.request

WAGO = "https://wago.tools"
WHITESPACE = re.compile(r"[ \t\r\n]+")
# Tokens this can't reproduce from live text: gendered ($g), class and race
# substitutions are ambiguous against ordinary words, so those rows are left out.
UNMATCHABLE = re.compile(r"\$[gGcCrR]")


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "SpeakStone build_voiced_lines"})
    with urllib.request.urlopen(req) as resp:
        return resp.read().decode("utf-8")


def latest_build(product):
    return json.loads(fetch(WAGO + "/api/builds/latest"))[product]["version"]


def normalise(text):
    text = text.replace("$N", "$n").replace("$B", " ").replace("$b", " ")
    return WHITESPACE.sub(" ", text).strip(" ")


def line_hash(text):
    h = 0
    for b in text.encode("utf-8"):
        h = (h * 31 + b) % 4294967296
    return h


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--build", help="client build, e.g. 12.1.0.69933 (default: latest for --product)")
    ap.add_argument("--product", default="wow",
                    help="wago product when --build is omitted: wow (retail), wow_classic_beta (Forever)")
    ap.add_argument("--out", default="VoicedLines.lua")
    args = ap.parse_args()

    build = args.build or latest_build(args.product)
    rows = csv.DictReader(io.StringIO(fetch(f"{WAGO}/db2/BroadcastText/csv?build={build}")))

    hashes, skipped, voiced = set(), 0, 0
    for row in rows:
        if row.get("SoundKitID_0", "0") == "0" and row.get("SoundKitID_1", "0") == "0":
            continue
        voiced += 1
        for field in ("Text_lang", "Text1_lang"):
            text = row.get(field) or ""
            if not text:
                continue
            if UNMATCHABLE.search(text):
                skipped += 1
                continue
            text = normalise(text)
            if text:
                hashes.add(line_hash(text))

    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write(f"-- Generated by tools/build_voiced_lines.py from BroadcastText {build}.\n")
        f.write("-- Hashes of NPC chat lines Blizzard has voiced. Do not edit; regenerate.\n")
        f.write('SpeakStone_VoicedLinesLocale = "enUS"\n')
        f.write("SpeakStone_VoicedLines = {\n")
        for h in sorted(hashes):
            f.write(f"[{h}]=1,\n")
        f.write("}\n")
    print(f"{build}: {voiced} voiced rows, {len(hashes)} hashes, {skipped} texts skipped (gender/class/race tokens) -> {args.out}",
          file=sys.stderr)


if __name__ == "__main__":
    main()
